"""ControlPlane.ai RLHF — Canonical Data Schema.

``PreferencePair`` is the single shared record shape used by *every*
file in this package.  Never construct ad-hoc dicts for the same
purpose — always construct, pass, and store ``PreferencePair`` objects.

Validated with pydantic v2.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from rlhf.config import Category


# ---------------------------------------------------------------------------
# Nested models
# ---------------------------------------------------------------------------

class ModelResponse(BaseModel):
    """One model's response to the shared prompt.

    Attributes:
        text: The raw text generated by the model.
        model_name: Human-readable model identifier (e.g. ``"gpt-4o-mini"``).
        model_version_or_checkpoint: Version string or local checkpoint path.
        hyperparameters: Generation settings (temperature, top_p, max_tokens…).
        is_error: True when the model call raised an exception.
        error_message: The exception message, populated only when ``is_error``
            is True.
    """

    text: str = ""
    model_name: str
    model_version_or_checkpoint: str = "unknown"
    hyperparameters: dict[str, Any] = Field(default_factory=dict)
    is_error: bool = False
    error_message: Optional[str] = None


# ---------------------------------------------------------------------------
# Top-level record
# ---------------------------------------------------------------------------

class PreferencePair(BaseModel):
    """A single (prompt, response_a, response_b) preference record.

    This is the *only* record shape written to and read from the data stores.
    Label fields (``chosen``, ``labeled_by``, ``labeled_at``) start as None
    and are filled in by a judge or human annotator.

    Attributes:
        pair_id: Globally unique UUID string assigned at creation time.
        session_id: Optional correlation handle linking pairs from the same
            user/agent session.
        prompt: The exact prompt text submitted to both models.
        response_a: Response from the first model (see ``ModelResponse``).
        response_b: Response from the second model.
        category: Domain the pair belongs to (``Category`` enum).  Defaults
            to ``UNSPECIFIED``; always validated through
            ``storage.categorize.assign_category`` before writing.
        chosen: Which side a judge preferred.  ``None`` = not yet labeled;
            ``"a"`` / ``"b"`` = one side preferred; ``"tie"`` = tie or
            disagreement between judge runs.
        labeled_by: Who/what applied the label (``"human"`` | ``"llm_judge"``
            | None).
        judge_metadata: Arbitrary dict — raw votes, prompt orderings, and any
            position-bias-control bookkeeping the judge wants to attach.
        created_at: UTC timestamp when the pair was first created.
        labeled_at: UTC timestamp when the pair was labeled (None until then).
        source_pipeline: Tag identifying which generator produced the pair
            (e.g. ``"api_vs_api"`` or ``"local_vs_local"``).
    """

    pair_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: Optional[str] = None
    prompt: str
    response_a: ModelResponse
    response_b: ModelResponse
    category: Category = Category.UNSPECIFIED
    chosen: Optional[Literal["a", "b", "tie"]] = None
    labeled_by: Optional[Literal["human", "llm_judge"]] = None
    judge_metadata: Optional[dict[str, Any]] = None
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    labeled_at: Optional[datetime] = None
    source_pipeline: str = "unknown"
    # Internal bookkeeping for the JSON store's append-and-reconcile strategy.
    # Readers must honour this field: "label_update" records supersede their
    # matching "initial" record for the same pair_id.
    record_type: Literal["initial", "label_update"] = "initial"

    model_config = {"use_enum_values": True}
